[project]
name = "Quiz-Back-FastAPI"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "fastapi>=0.124.2",
  "uvicorn>=0.38.0",
  "sqlmodel>=0.0.22",         # SQLAlchemy 2.x + Pydantic v2, parfait pour SQLite
  "pydantic-settings>=2.5",
]

[tool.ruff]
line-length = 100